version: '3'
services:
  db:
    image: mysql:5.7
    build:
      context: .
      dockerfile: mysql/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
  web:
    build:
      context: .
      dockerfile: rails/Dockerfile
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    command: ./bin/server
    volumes:
      - .:/giglog:cached
      - bundle:/bundle
    ports:
      - 3000:3000
    depends_on:
      - db
    tty: true
    stdin_open: true
volumes:
  bundle:
    driver: local
